### ISSUE TITLE
Sometimes specific files can't be copied using lftp?

### ISSUE THREAD

**Issue by ectorhga** [GrapheneCt/BGFTP#1]
Hi,

I'm trying to buld an automatic sync of savefiles between PSV and PSTV. So far, I manually connected to the PSV with lftp running from a Rasperry Pi.
Now, when I try to mirror the savedata folder to the pi, I get some errors, that some files cannot be found (usually these are .icv files in the subdirectories /ux0:/user/00/savedata/GAMENAME/sce_pfs/icv.db/ ).
When I rerun the mirror command, the outcome is the same with the same files then went "missing" (they are there, of course, I checked).

I've also tried mirroring the savegames with the FTP server of VitaShell and that produced no errors whatsoever.
Do you maybe know, what I might have missed?

**Comment by GrapheneCt** [comment]
BGFTP locks its own savedata directory (BGFTP010) and the directory of the currently running application will also be locked. If any other directories are affected, can you provide their title id?

**Comment by ectorhga** [comment]
Sure. IIRC there were problems with the BGFTP010 folder, but lots others were affected as well. I think ist was mostly those .icv files.

After I mirrored the safedata folder with vitashells FTP, I made another mirror run with BGFTP and that went well (with only some those files in the BGFTP010 that didn't copy over). 

I then played DanganRonpa (PCSE00261) and saved. Running another mirror with BGFTP produced new copy errors. Vitashells FTP once more allowed the copying. 

I'm sorry if that info is too vague... I'm not a programmer myself, so I'm not sure what to look after. ;) I can try to make another test tonight. Maybe if I delete my local folder and do the mirror from scratch?

**edit**

I just reread your comment, and the PCSE00261 folder was probably locked, too. Hmm. But I'm sure, a lot of ther files/folders were not copied over in my first attempt. So I will delete the local folder and start from scratch to see if the errors are reproducible.

**Comment by ectorhga** [comment]
OK. I tried again, and for **every**  XXX.icv file I get this error message:
`mirror: Access failed: 550 File not found. (XXX.icv)`

The files are definitely there...

**edit** spelling

**Comment by GrapheneCt** [comment]
It seems that Vita locks all pfs-related savedata files when application with PAID other than SceShell (like BGFTP) is running.

Will try to fix this in the next version, however I am not sure if BGFTP will work properly with different PAID.
