### ISSUE TITLE
Feature suggestion - network check and wifi activation

### ISSUE THREAD

**Issue by pixeltester** [GrapheneCt/BGFTP#3]
My suggestion is as follows: check network state when the BGFTP application is started, start wi-fi if required then wait until connected before allowing BGFTP process start. Also if possible remove the need to press x when the app is started, just launch the process and exit automatically.

Benefits: 

- one click background FTP running from scratch even if wi-fi not activated
- no forgetting to activate wi-fi and starting a dead BGFTP service

Thanks for the great tool.

**Comment by GrapheneCt** [comment]
Partially fixed in v1.5

**Comment by GrapheneCt** [comment]
Added network connection check in v2.0
