### ISSUE TITLE
Not working on PS TV

### ISSUE THREAD

**Issue by AntonioDePau** [GrapheneCt/BGFTP#5]
Seems like this is not behaving as expected on PS TV. I just installed it the exact same way on PS Vita and it worked flawlessly, but not on my PS TV.

Affected version: **3.21**

**System info:**
PS TV model: VTE-1016
Software: 3.60 (downgraded from 3.73)

**Steps to reproduce:**

Install:
1. Copy vpk to ux0:/data
2. Start VitaShell
3. Go to ux0:/data
4. Highlight the vpk file
5. Press "X"
6. Confirm install
7. Confirm (security warning)
8. Installation reaches 100%

Launch:
1. Go back to the Live Area
2. Start BGFTP
3. "Closes" soon after starting
4. Keeps saying "Start" instead of "Continue". No BGFTP notification with IP and port

**Already tried:**

- [x] Rebooting device
- [x] Uninstalling BGFTP and reinstalling

**Comment by AntonioDePau** [comment]
~~Could it be related to the fact that the PS TV does not have Flight Mode?~~
https://github.com/GrapheneCt/BGFTP/blob/872cd18c72513ef3f3b68e8c7a850a75275e115a/BGFTP_bgapp/main.c#L101
~~Which could make the app crash if it's trying to retrieve a value that is not set in the system config?
(I have no idea how the Vita/TV OS works, shooting in the dark here, or maybe pointing out the obvious, bear with me please!)~~

Edit: formatting & "Plane" --> "Flight"

Nevermind, seems like flight_mode is present on PS TV registry too, unless I'm looking in the wrong place:
<img src="https://user-images.githubusercontent.com/23122727/113517656-45d37700-9579-11eb-9aac-d62fc5e68d25.png" width="400">

**Comment by GrapheneCt** [comment]
Sorry for the delay answering this. Flight mode key is indeed present in PS TV. I also have PS TV and it works fine for me. "Start" instead of "Continue" on gate is normal. Please try v3.23

**Comment by AntonioDePau** [comment]
> Sorry for the delay answering this. Flight mode key is indeed present in PS TV. I also have PS TV and it works fine for me. "Start" instead of "Continue" on gate is normal. Please try v3.23

Hey, no worries, we're all busy!

So, I tried, issue still occurs for me.
However, I checked the version of the homebrew after installing, it still says 3.**21** (Triangle on bubble, triangle again, "Information"). I've tried uninstalling and making sure I downloaded the correct .vpk and tried again, still the same.

Could it be that you've uploaded the incorrect version? Or is it simply still displaying the old version under information?

**Comment by GrapheneCt** [comment]
Version is correct, I just forgot to update number for vpk. After installing app, do you see it in Settings->Notifications?

**Comment by AntonioDePau** [comment]
Yes, and both "Show on Screen" and "Play Sound" are ticked.

**Comment by GrapheneCt** [comment]
Upload your config.txt. I think some plugin might be preventing it from launching.

**Comment by AntonioDePau** [comment]
Could be, here goes: [config.txt](https://github.com/GrapheneCt/BGFTP/files/6409597/config.txt)

**Comment by GrapheneCt** [comment]
That's very clean. I don't see anything wrong there. Usually people tend to put some stuff under *ALL that may break some apps. Once I get home I'll build a debug version for you so it will be possible to see where exactly it fails.

**Comment by GrapheneCt** [comment]
[eboot2.zip](https://github.com/GrapheneCt/BGFTP/files/6409854/eboot2.zip)
Replace file in ux0:app/GRVA00001 with this one. You should see some additional debug notifications. For normal operation, the order should be:
```
[BG] process start ok
[BG] passed network check
[BG] module init done
[BG] ftpvita: adding devices
IP: Port:

**Comment by AntonioDePau** [comment]
Mhh, so, I replaced ux0:app/GRVA00001/eboot2.bin with the one in the zip you shared.
Nothing happened. Restarted the PsTV, tried starting BGFTP again, nothing (to be clear, I press "X" on BGFTP, and then "X" on "Start", it goes to fullscreen and just back to the "Start" screen almost instantly. No notifications, nothing).

**Comment by GrapheneCt** [comment]
Either bg app just doesn't start or notifications are broken on your system for some reason. I don't really know why that might happen. Try installing [ioplus](https://github.com/CelesteBlue-dev/PSVita-RE-tools/blob/master/ioPlus/ioPlus-0.1/release/ioplus.skprx) and see if anything changes.

**Comment by NO-ob** [comment]
I'm also having issues with pstv the application starts then goes back to menu. There is an icon at the top showing the logo but I am unable to connect via ftp is the port different to what vitashell uses? I'm on 3.65 enso and added the lowmem plugin
