### ISSUE TITLE
550 error from my FTP client when trying to access ux0:Music/

### ISSUE THREAD

**Issue by rmsa5** [GrapheneCt/BGFTP#6]
Can't browse ux0:Music/ thought it is perfectly accessible through vitashell's FTP server, and no SDcard integrity error when scanned on my computer. I have no idea what extra info I can provide. I am happy to narrow down the issue if you have any idea. Thanks in advance

**Comment by GrapheneCt** [comment]
This is the same error that affects official music player application with sd2vita. It is not related to BGFTP implementation. Before accesing ux0:music make sure you don't have other apps that use this folder opened. If it still won't work than this issue can not be fixed on BGFTP side.
