### ISSUE TITLE
Limit background threads?

### ISSUE THREAD

**Issue by ticky** [GrapheneCt/BGFTP#7]
First of all thanks so much for this invaluable tool!

I've noticed that modern FTP clients like to use a bunch of threads to transfer lots of files quickly, but this quickly overwhelms BGFTP, I presume due to having a constrained amount of RAM due to being in the background. It's usually possible to reconfigure them to limit the threading to something more reasonably like 5 at a time, but it's not foolproof.

I don't know for sure it would _fix_ it, but from reading how FTP intends to work it seems to me [the 500 error thrown in this instance](https://github.com/GrapheneCt/BGFTP/blob/8b1bb91fab6e0a66156ce1b8bc0fe931289e1edb/BGFTP_bgapp/ftpvita.c#L520-L524) might be better to instead return a 4xx code (like 425, "Can't open data connection", for example) which indicates to clients that there's a resource issue and that it can be retried.

**Comment by GrapheneCt** [comment]
Will consider that. BGFTP has access only to 16MiB of RAM, with current file buffer size this allows only 3 simultaneous transfers.

**Comment by GrapheneCt** [comment]
Since v3.24 BGFTP will adjust operation buffer size dynamically to allow more simultaneous operations.
